name: test

on:
    workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2